name: test-actions
on: push
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile unit tests with Maven
        run: mvn test-compile
      - name: run project
        run: mvn exec:java -Dexec.mainClass=org.example.Main &
      - name: Run unit test
        run: mvn test
      - name: Integration testing
        run: mvn -Dskip.ut=true verify
      - name: exit from console
        run: exit