name: test-actions
#on: pull_request
on: push
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile unit tests with Maven
        run: mvn test-compile
      - name: Run unit test with Maven
        run: mvn -X -e -Dtest=MainTest test
#      - name: Compile project
#        run: javac -cp $(mvn -q dependency:build-classpath -Dmdep.outputFile=/dev/fd/1) src/main/java/org/example/Main.java
      - name: run project
        run: mvn exec:java -Dexec.mainClass=org.example.Main $
      - name: run integration tests
        run: mvn -X -e -Dtest=SparkIntegrationTest test
      - name: exit from console
        run: exit




