name: test-actions
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile unit tests with Maven
        run: mvn test-compile
      - name: Run unit test
        run: mvn -Dtest=MainTest test
      - name: Integration testing
        run: mvn -Dtest=WebSocketHandlerTest test
      - name: exit from console
        run: exit