name: test-actions
#on: pull_request
on: push
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile unit tests with Maven
        run: mvn test-compile
      - name: Run unit and integration test with Maven
        run: mvn -X -e -Dtest=MainTest test
      - name: exit from console
        run: exit




